---
output:
  pdf_document:
    toc: false
    latex_engine: xelatex
  html_document:
    toc: false
    paged: false
header-includes: \usepackage{fontspec, pdfpages, graphicx} \setmainfont{Times New Roman} \pagestyle{empty}
---

```{r setup, include=FALSE, message=FALSE, echo=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(grid)
library(gridExtra)
library(ggpubr)
library(here)
library(ggrepel)
library(showtext) # so arrows and delta are rendered properly
showtext_auto()
library(scales)
library(patchwork)
library(igraph)
library(tidygraph)
library(ggraph)

source(here("src/helpers_pageRank.R"))
source(here("src/helpers_exposure-modifier.R"))

parse_means <- function(pheno_dat, gene_meth, genes){
  dat <- gene_meth %>%
    dplyr::filter(gene_primary %in% genes)  %>%# filter out genes in proximity hub
    column_to_rownames(var = "gene_primary") %>%
    dplyr::select(-n_cpg) %>%
    t() %>%
    as.data.frame() %>%
    rownames_to_column(var = "basename") 
  dat <- dplyr::left_join(pheno_dat, dat, by = "basename")
  return(dat)
}

# Helper for parsing singscore output
parse_sing <- function(pheno_dat, score_df) {
  dat2 <- scoredf$Scores %>%
    t() %>%
    as.data.frame() %>%
    rownames_to_column(var = "basename")
  dat2 <- dat2[, colSums(is.na(dat2)) == 0]
  outcomes <- colnames(dat2)[-1]
  
  pdat <- dplyr::full_join(pheno_dat, dat2)
  
  return(list(pdat,outcomes))
}

parse_hubmeans <- function(pheno_dat, path_mean_scores){
  dat2 <- path_mean_scores %>%
    dplyr::rename(basename = Sample) %>%
    pivot_wider(id_cols = basename, names_from = Hub, values_from = Score)
  pdat <- dplyr::left_join(pheno_dat, dat2)
  return(pdat)
}


```

```{r}

# Pheno #----
load(here("data/pheno.Rdata"))

pheno_sub <- droplevels(pheno[pheno$Experiment=='exp5' & pheno$Tissue.type %in% c('Breast'),])

# Reformat for 2x2x2 design, and diet groups for raw plots
dat <- pheno_sub %>%
  mutate(
    exposure      = factor(ifelse(grepl("\\bMPA/DMBA\\+", Treatment), 1, 0),
                           levels = c(0, 1), labels = c("P/D-", "P/D+")),
    keto          = factor(ifelse(grepl("\\bKD\\+",       Treatment), 1, 0),
                           levels = c(0, 1), labels = c("KD-", "KD+")),
    mifepristone  = factor(ifelse(grepl("\\bMIF\\+",      Treatment), 1, 0),
                           levels = c(0, 1), labels = c("MIF-", "MIF+"))
  ) %>%
  mutate(
    diet4 = factor(
      paste0(keto, " ", mifepristone),
      levels = c("KD- MIF-",  "KD+ MIF-", "KD- MIF+", "KD+ MIF+")
    )
  ) %>%
  dplyr::select(basename,exposure,keto,mifepristone,diet4)

pc_scores <- readRDS(here("results/analysis2_celltype_adj/2-output/celltype_pc_scores.Rds"))
dat <- full_join(dat, pc_scores[,1:5])
covars <- colnames(pc_scores[,1:5])[-1]

# DMP results baseline
dmp_base <- readRDS(here("results/analysis2_celltype_adj/2-output/breast_limma_celltype_adj.Rds")) %>%
  dplyr::filter(keto == "KD-" & mifepristone == "MIF+")
dmp_base$outcome <- gsub("_logit","", dmp_base$outcome)
anno <- readRDS(here("results/0-output/anno2_genes_filtered.Rds"))
dmp_base <- left_join(dmp_base,anno, by = c("outcome" = "Name"))

dmp_prom <- dmp_base %>% dplyr::filter(promoter == TRUE & p.adj_cell < 0.05) %>% pull(ENTREZID) %>% unique() %>% na.omit() #310 gene prim, 294 entrez
dmp_body <- dmp_base %>% dplyr::filter(promoter == FALSE & p.adj_cell < 0.05) %>% pull(ENTREZID) %>% unique() %>% na.omit() #498 gene prim, 468 entrez

# gene_primary, entrez
annot <- anno %>%
  dplyr::select(gene_primary, ENTREZID) %>%
  distinct() #27031

id2symbol <- setNames(
  annot$gene_primary,
  annot$ENTREZID
)

# Gene-level summary methy base, IPW for CpG correction
dat_base <- readRDS(here("results/analysis2_celltype_adj/3-output/gene_base_meta_universe.Rds")) %>%
  dplyr::left_join(annot, by = "gene_primary") %>%
  dplyr::filter(ENTREZID %in% c(dmp_prom, dmp_body)) # focus on genes with DMP

# Seed proximity info #----
configs <- list(
  list(file = "ppr_pr_ext.Rds",          title = "PR regulatory network"),
  list(file = "ppr_rankl_nfbk.Rds",      title = "RANKL–NF-κB"),
  list(file = "ppr_wnt_ext.Rds",         title = "Wnt/β-catenin signaling"),
  list(file = "ppr_ccnd1_ext.Rds",       title = "CCND1/cell-cycle"),
  list(file = "ppr_prl_stat5.Rds",       title = "PRL–JAK2–STAT5 signaling"),
  list(file = "ppr_pi3k_akt_mtor.Rds",   title = "PI3K–AKT–mTOR signaling"),
  list(file = "ppr_survival_nfkb.Rds",   title = "NF-κB survival")
)
base_path <- here("results/2-output/")
 
annot <- readRDS(here("results/0-output/anno2_genes_filtered.Rds"))

id2symbol <- setNames(
  annot$gene_primary,
  annot$ENTREZID
)

# gene summaries bulk #-----

gene_meth_prom <- readRDS("results/analysis2_celltype_adj/6-output/island_breast_genemeanmeth_promoters.Rds")
gene_meth_body <- readRDS("results/analysis2_celltype_adj/6-output/island_breast_genemeanmeth_genebody.Rds")

# gene summaries cell type compartments #-----

gene_met_epi_prom <- readRDS(here("results/analysis3_tensor/1-output/base_epi_genemeanmeth_promoters.Rds"))
gene_met_imm_prom <- readRDS(here("results/analysis3_tensor/1-output/base_imm_genemeanmeth_promoters.Rds"))
gene_met_stro_prom <- readRDS(here("results/analysis3_tensor/1-output/base_stro_genemeanmeth_promoters.Rds"))
gene_met_epi_body <- readRDS(here("results/analysis3_tensor/1-output/base_epi_genemeanmeth_genebody.Rds"))
gene_met_imm_body <- readRDS(here("results/analysis3_tensor/1-output/base_imm_genemeanmeth_genebody.Rds"))
gene_met_stro_body <- readRDS(here("results/analysis3_tensor/1-output/base_stro_genemeanmeth_genebody.Rds"))

```

```{r}

# Example plot PPR
ranked <- readRDS(here("results/2-output/ppr_rankl_nfbk.Rds"))
p1 <- plot_ppr_base_pval_logfold(
      ranked, dat_base,
      promoter_var = TRUE,
      seed_tit = "RANKL–NF-κB",
      top_genes = 10
    ) + ggtitle("pCGIs")

```

```{r}

pdat <- readRDS(here("results/analysis2_celltype_adj/13-output/ppr_proximal_genes.Rds")) %>%
  dplyr::mutate(gene_region = case_when(promoter == TRUE ~ "pCGI", TRUE ~ "oCGI")) %>%
  count(gene_region, seed) %>%
  arrange(desc(n))
pdat$seed <- factor(pdat$seed, levels = rev(unique(pdat$seed)))

p2 <- ggplot(pdat, aes(x = seed, y = n, fill = gene_region)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() +
  labs(
    x = "",
    y = "Number of proximal DMGs",
    fill = ""
  ) +
  scale_fill_manual(values = c("darkslategray4","darkkhaki")) +
  theme_classic() + 
  theme(legend.position = "bottom")

```

```{r}

# highlight shared genes

seeds.genes <- readRDS(here("results/analysis2_celltype_adj/13-output/ppr_proximal_genes.Rds")) %>%
  dplyr::select(-promoter) %>%
  distinct()

shared_genes <- seeds.genes %>%
  count(gene_primary) %>%
  filter(n >= 2) %>%
  pull(gene_primary)

# Keep only edges to shared genes (removes edges to unique genes)
edges <- seeds.genes %>%
  filter(gene_primary %in% shared_genes) %>%
  transmute(from = seed, to = gene_primary)

# Node tables
nodes_genes <- seeds.genes %>%
  filter(gene_primary %in% shared_genes) %>%
  distinct(gene_primary) %>%
  mutate(type = "gene", shared = "shared") %>%
  dplyr::rename(name = gene_primary)

nodes_seeds <- seeds.genes %>%
  distinct(seed) %>%
  transmute(name = seed, type = "seed")

# Graph
g <- graph_from_data_frame(
  edges,
  vertices = bind_rows(nodes_seeds, nodes_genes),
  directed = FALSE
)
tg <- as_tbl_graph(g)

set.seed(123)  # for reproducible layout
p3 <- ggraph(tg, layout = "stress") +
  # edges
  geom_edge_link(alpha = 0.3) +

  # seed nodes (hubs)
  geom_node_point(aes(filter = type == "seed"),
                  size = 4, shape = 15, color = "darkslategrey") +

  # gene nodes: SHARED (highlighted)
  geom_node_point(aes(filter = type == "gene" & shared == "shared"),
                  color = "orchid4", size = 2) +

  # labels only for shared genes
  geom_node_text(aes(label = name,
                     filter = type == "gene" & shared == "shared"),
                 repel = TRUE, size = 3, fontface = "italic") +
  
  # labels: seed nodes only
  geom_node_text(aes(label = name, filter = type == "seed"),
                 repel = TRUE, size = 4, color = "darkslategrey") +

  theme_void()

```

```{r}

crosstalk_genes <- seeds.genes %>%
  count(gene_primary) %>%
  filter(n >= 3) %>%
  pull(gene_primary)

seeds.genes <- readRDS(here("results/analysis2_celltype_adj/13-output/ppr_proximal_genes.Rds")) %>%
  dplyr::filter(gene_primary %in% crosstalk_genes)

# Prep Tissue-wide and cell compartment maps
list_tissue <- list()
list_comp <- list()

# Promoter  
outcomes <- seeds.genes %>% dplyr::filter(promoter == TRUE) %>% pull(gene_primary)
  
list_tissue[[1]] <- parse_means(dat, gene_meth_prom, outcomes)
  
pdat_epi <- parse_means(dat, gene_met_epi_prom, outcomes)
pdat_imm <- parse_means(dat, gene_met_imm_prom, outcomes)
pdat_stro <- parse_means(dat, gene_met_stro_prom, outcomes)
list_comp[[1]] <- setNames(list(pdat_epi, pdat_imm, pdat_stro), c("Epi", "Imm", "Stro"))

# Gene body 
outcomes <- seeds.genes %>% dplyr::filter(promoter == FALSE) %>% pull(gene_primary)
  
list_tissue[[2]] <- parse_means(dat, gene_meth_body, outcomes)
  
pdat_epi <- parse_means(dat, gene_met_epi_body, outcomes)
pdat_imm <- parse_means(dat, gene_met_imm_body, outcomes)
pdat_stro <- parse_means(dat, gene_met_stro_body, outcomes)
list_comp[[2]] <- setNames(list(pdat_epi, pdat_imm, pdat_stro), c("Epi", "Imm", "Stro"))

# Combined plot #--------------
outcomes <- unique(seeds.genes$gene_primary)
outcome_labels <- NULL
p4 <- wrap_summary_plot_multi3(list_tissue,
                               list_comp,
                               c("pCGI","oCGI"),
                               outcomes,
                               outcome_labels,
                               covars = covars,
                               drop_ns = T)
p4_grob <- ggplotify::as.grob(p4) 

```

```{r, fig.height=12, fig.width=12}

# combine plots #----
invisible(grid.arrange(
  grobs = list(
    arrangeGrob(p1, top = textGrob(
      "a",
      gp = gpar(fontsize = 12, fontface = "bold"),
      x = unit(0, "npc"),
      hjust = 0
    )),
    arrangeGrob(p2, top = textGrob(
      "b",
      gp = gpar(fontsize = 12, fontface = "bold"),
      x = unit(0, "npc"),
      hjust = 0
    )),
    arrangeGrob(p3, top = textGrob(
      "c",
      gp = gpar(fontsize = 12, fontface = "bold"),
      x = unit(0, "npc"),
      hjust = 0
    )),
    arrangeGrob(p4_grob, top = textGrob(
      "d pCGIs",
      gp = gpar(fontsize = 12, fontface = "bold"),
      x = unit(0, "npc"),
      hjust = 0
    ))
  ),
  layout_matrix = rbind(c(1,2),
                        c(3,4))
))


```


