---
output:
  pdf_document:
    toc: false
    latex_engine: xelatex
  html_document:
    toc: false
    paged: false
header-includes: \usepackage{fontspec, pdfpages, graphicx} \setmainfont{Times New Roman} \pagestyle{empty}
---

```{r setup, include=FALSE, message=FALSE, echo=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(grid)
library(gridExtra)
library(ggpubr)
library(here)
library(ggrepel)
library(showtext) # so arrows and delta are rendered properly
showtext_auto()
library(scales)
library(patchwork)
library(igraph)
library(tidygraph)
library(ggraph)

source(here("src/helpers_pageRank.R"))
source(here("src/helpers_exposure-modifier.R"))

parse_means <- function(pheno_dat, gene_meth, genes){
  dat <- gene_meth %>%
    dplyr::filter(gene_primary %in% genes)  %>%# filter out genes in proximity hub
    column_to_rownames(var = "gene_primary") %>%
    dplyr::select(-n_cpg) %>%
    t() %>%
    as.data.frame() %>%
    rownames_to_column(var = "basename") 
  dat <- dplyr::left_join(pheno_dat, dat, by = "basename")
  return(dat)
}


```

```{r}

# Pheno #----
load(here("data/pheno.Rdata"))

pheno_sub <- droplevels(pheno[pheno$Experiment=='exp5' & pheno$Tissue.type %in% c('Breast'),])

# Reformat for 2x2x2 design, and diet groups for raw plots
dat <- pheno_sub %>%
  mutate(
    exposure      = factor(ifelse(grepl("\\bMPA/DMBA\\+", Treatment), 1, 0),
                           levels = c(0, 1), labels = c("P/D-", "P/D+")),
    keto          = factor(ifelse(grepl("\\bKD\\+",       Treatment), 1, 0),
                           levels = c(0, 1), labels = c("KD-", "KD+")),
    mifepristone  = factor(ifelse(grepl("\\bMIF\\+",      Treatment), 1, 0),
                           levels = c(0, 1), labels = c("MIF-", "MIF+"))
  ) %>%
  mutate(
    diet4 = factor(
      paste0(keto, " ", mifepristone),
      levels = c("KD- MIF-",  "KD+ MIF-", "KD- MIF+", "KD+ MIF+")
    )
  ) %>%
  dplyr::select(basename,exposure,keto,mifepristone,diet4)

pc_scores <- readRDS(here("results/analysis2_celltype_adj/2-output/celltype_pc_scores.Rds"))
dat <- full_join(dat, pc_scores[,1:5])
covars <- colnames(pc_scores[,1:5])[-1]


# Seed proximity info #----
configs <- list(
  list(file = "ppr_pr_ext.Rds",          title = "PR regulatory network"),
  list(file = "ppr_rankl_nfbk.Rds",      title = "RANKL–NF-κB"),
  list(file = "ppr_wnt_ext.Rds",         title = "Wnt/β-catenin signaling"),
  list(file = "ppr_ccnd1_ext.Rds",       title = "CCND1/cell-cycle"),
  list(file = "ppr_prl_stat5.Rds",       title = "PRL–JAK2–STAT5 signaling"),
  list(file = "ppr_pi3k_akt_mtor.Rds",   title = "PI3K–AKT–mTOR signaling"),
  list(file = "ppr_survival_nfkb.Rds",   title = "NF-κB survival")
)
base_path <- here("results/2-output/")

# gene summaries bulk #-----

gene_meth_prom <- readRDS(here("results/analysis2_celltype_adj/6-output/island_breast_genemeanmeth_promoters.Rds"))
gene_meth_body <- readRDS(here("results/analysis2_celltype_adj/6-output/island_breast_genemeanmeth_genebody.Rds"))

# gene summaries cell type compartments #-----

gene_met_epi_prom <- readRDS(here("results/analysis3_tensor/1-output/base_epi_genemeanmeth_promoters.Rds"))
gene_met_imm_prom <- readRDS(here("results/analysis3_tensor/1-output/base_imm_genemeanmeth_promoters.Rds"))
gene_met_stro_prom <- readRDS(here("results/analysis3_tensor/1-output/base_stro_genemeanmeth_promoters.Rds"))
gene_met_epi_body <- readRDS(here("results/analysis3_tensor/1-output/base_epi_genemeanmeth_genebody.Rds"))
gene_met_imm_body <- readRDS(here("results/analysis3_tensor/1-output/base_imm_genemeanmeth_genebody.Rds"))
gene_met_stro_body <- readRDS(here("results/analysis3_tensor/1-output/base_stro_genemeanmeth_genebody.Rds"))

```

```{r}

# Promoter #-----------------

seeds.genes <- readRDS(here("results/analysis2_celltype_adj/13-output/ppr_proximal_genes.Rds")) %>% dplyr::filter(promoter == TRUE)
sig.seeds <- c("PR regulatory network", "RANKL–NF-κB", "Wnt/β-catenin signaling", 
               "PRL–JAK2–STAT5 signaling", "CCND1/cell-cycle", "PI3K–AKT–mTOR signaling", "NF-κB survival")
sig.seeds2 <- gsub("PI3K–AKT–mTOR signaling","PAM",sig.seeds)

# Prep Tissue-wide and cell compartment maps
list_tissue <- list()
list_comp <- list()
for (i in 1:length(sig.seeds)) {
  
  outcomes <- seeds.genes %>% dplyr::filter(seed == sig.seeds[i]) %>% pull(gene_primary)
  
  list_tissue[[i]] <- parse_means(dat, gene_meth_prom, outcomes)
  
  pdat_epi <- parse_means(dat, gene_met_epi_prom, outcomes)
  pdat_imm <- parse_means(dat, gene_met_imm_prom, outcomes)
  pdat_stro <- parse_means(dat, gene_met_stro_prom, outcomes)
  list_comp[[i]] <- setNames(list(pdat_epi, pdat_imm, pdat_stro), c("Epi", "Imm", "Stro"))
}

# Combined plot #--------------
outcomes <- unique(seeds.genes$gene_primary)
outcome_labels <- NULL
p4 <- wrap_summary_plot_multi3(list_tissue,
                               list_comp,
                               sig.seeds2,
                               outcomes,
                               outcome_labels,
                               covars = covars,
                               drop_ns = T)
p4_grob <- ggplotify::as.grob(p4) 

# Gene body #-----------------

seeds.genes <- readRDS(here("results/analysis2_celltype_adj/13-output/ppr_proximal_genes.Rds")) %>% dplyr::filter(promoter == FALSE)
sig.seeds <- c("PR regulatory network", "RANKL–NF-κB", "Wnt/β-catenin signaling", 
               "PRL–JAK2–STAT5 signaling", "CCND1/cell-cycle", "PI3K–AKT–mTOR signaling", "NF-κB survival")
sig.seeds2 <- gsub("PI3K–AKT–mTOR signaling","PAM",sig.seeds)

# Prep Tissue-wide and cell compartment maps
list_tissue <- list()
list_comp <- list()
for (i in 1:length(sig.seeds)) {
  
  outcomes <- seeds.genes %>% dplyr::filter(seed == sig.seeds[i]) %>% pull(gene_primary)
  
  list_tissue[[i]] <- parse_means(dat, gene_meth_body, outcomes)
  
  pdat_epi <- parse_means(dat, gene_met_epi_body, outcomes)
  pdat_imm <- parse_means(dat, gene_met_imm_body, outcomes)
  pdat_stro <- parse_means(dat, gene_met_stro_body, outcomes)
  list_comp[[i]] <- setNames(list(pdat_epi, pdat_imm, pdat_stro), c("Epi", "Imm", "Stro"))
}

# Combined plot #--------------
outcomes <- unique(seeds.genes$gene_primary)
outcome_labels <- NULL
p5 <- wrap_summary_plot_multi3(list_tissue,
                               list_comp,
                               sig.seeds2,
                               outcomes,
                               outcome_labels,
                               covars = covars,
                               drop_ns = T)
p5_grob <- ggplotify::as.grob(p5) 


```

```{r, fig.height=21, fig.width=16}

# combine plots #----
invisible(grid.arrange(
    arrangeGrob(p4_grob, top = textGrob(
      "a pCGIs",
      gp = gpar(fontsize = 12, fontface = "bold"),
      x = unit(0, "npc"),
      hjust = 0
    )),
    arrangeGrob(p5_grob, top = textGrob(
      "b oCGIs",
      gp = gpar(fontsize = 12, fontface = "bold"),
      x = unit(0, "npc"),
      hjust = 0
    )),
  layout_matrix = rbind(c(1,2))
))

```

