---
output:
  pdf_document:
    toc: false
    latex_engine: xelatex
  html_document:
    toc: false
    paged: false
header-includes: \usepackage{fontspec, pdfpages, graphicx} \setmainfont{Times New Roman} \pagestyle{empty}
---

```{r setup, include=FALSE, message=FALSE, echo=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(patchwork)
library(emmeans)
library(here)
library(showtext) # so arrows and delta are rendered properly
showtext_auto()
library(grid)
library(gridExtra)
library(reshape2)

```

```{r, fig.height=4.5, fig.width=8}

source(here("src/helpers_exposure-modifier.R"))
source(here("src/clr_ilr_transform.R"))

# Data load #----
load(here("data/pheno.Rdata"))
dat <- droplevels(pheno[pheno$Experiment=='exp5' &
                          pheno$Tissue.type %in% c('Breast'),])

# Reformat for 2x2x2 design, and diet groups for raw plots
dat <- dat %>%
  mutate(
    exposure      = factor(ifelse(grepl("\\bMPA/DMBA\\+", Treatment), 1, 0),
                           levels = c(0, 1), labels = c("P/D-", "P/D+")),
    keto          = factor(ifelse(grepl("\\bKD\\+",       Treatment), 1, 0),
                           levels = c(0, 1), labels = c("KD-", "KD+")),
    mifepristone  = factor(ifelse(grepl("\\bMIF\\+",      Treatment), 1, 0),
                           levels = c(0, 1), labels = c("MIF-", "MIF+"))
  ) %>%
  mutate(
    diet4 = factor(
      paste0(keto, " ", mifepristone),
      levels = c("KD- MIF-", "KD- MIF+", "KD+ MIF-", "KD+ MIF+")
    )
  ) 

# Combine fat and fibroblasts, set outcomes
dat$EpiFibFatIc_Stromal <- dat$EpiFibFatIc_Fat + dat$EpiFibFatIc_Fib
dat <- dat[, !colnames(dat) %in% c("EpiFibFatIc_Fat", "EpiFibFatIc_Fib")]

outcome_cols <- colnames(dat)[grepl("EpiFibFatIc",colnames(dat))]
outcome_cols1 <- c("EpiFibFatIc_Epi","EpiFibFatIc_IC","EpiFibFatIc_Stromal")
outcome_cols2 <- setdiff(outcome_cols, outcome_cols1[1:2])



# B All subtypes #-----------------

clr_df <- clr_transform(dat,outcome_cols2, c("exposure","keto","mifepristone","diet4"))

labels <- c(
    "EpiFibFatIc_basal" = 'Basal cells',
    "EpiFibFatIc_luminal_progenitor"= 'Luminal progenitor cells',
    "EpiFibFatIc_mature_luminal"= 'Mature luminal cells',
    "EpiFibFatIc_B" = 'B cells',
    "EpiFibFatIc_CD4T" = 'CD4 T cells',
    "EpiFibFatIc_CD8T" = 'CD8 T cells',
    "EpiFibFatIc_MDSC" = 'MDSCs',
    "EpiFibFatIc_Neutro" = 'Neutrophils',
    "EpiFibFatIc_NK" = 'NK cells',
    "EpiFibFatIc_Stromal" = 'Stroma'
  )

p1 <- wrap_summary_plot(clr_df, names(labels), unname(labels))[[1]]
p1_grob <- ggplotify::as.grob(p1) 

```

```{r}


clr_df <- clr_transform(dat,outcome_cols2, c("basename","exposure","keto", "mifepristone", "diet4"))

load(here('results/analysis2_celltype_adj/2-output/pca.Rdata'))
s <- summary(pca) 
pc_scores <- pca$x %>% as.data.frame() %>% rownames_to_column(var = "basename")

pdat <- clr_df %>% 
  left_join(pc_scores) 

diet4_colors <- c('#009392','#9ccb86','#eeb479','#cf597e') 

# Plot
pc_plot <- pdat %>%
  ggplot(aes(x = PC1, y = PC2, shape = exposure, color = diet4)) +
  geom_point() +
  scale_color_manual(values = diet4_colors) +
  theme_classic()

pdat <- clr_df %>%
  dplyr::select(-keto, -mifepristone) %>%
  dplyr::select(-any_of(outcome_cols2)) %>%
  left_join(pc_scores) %>%
  melt(id.vars = c("basename","exposure","diet4"), variable.name = "PC", value.name = "score")

relabel <- paste0(names(s$importance[2,])," (", round(unname(s$importance[2,])*100, digits = 0), "%)") 
names(relabel) <- names(s$importance[2,])

p2 <- pdat %>%
  dplyr::filter(PC %in% c("PC1","PC2","PC3","PC4")) %>%
  ggplot(aes(x = exposure, y = score, group = exposure, shape = exposure, color = diet4)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +
  geom_jitter(width = 0.2, size = 2, alpha = 0.9) +
  facet_wrap(~PC, scales = "free_y", labeller = labeller(PC = relabel), ncol = 4) +
  scale_color_manual(values = diet4_colors) +
  labs(x = "Exposure", y = "PC score", color = "", shape = "") +
  theme_classic()

# Check loadings to find which cell type changes are dominant
loadings <- pca$rotation  

# Sort contributing cell types per PC
PC1_top <- sort(abs(loadings[, "PC1"]), decreasing = TRUE)
PC2_top <- sort(abs(loadings[, "PC2"]), decreasing = TRUE)
PC3_top <- sort(abs(loadings[, "PC3"]), decreasing = TRUE)
PC4_top <- sort(abs(loadings[, "PC4"]), decreasing = TRUE)

#Create a data frame for plotting
top_df <- data.frame(
  CellType = rep(names(c(PC1_top, PC2_top, PC3_top, PC4_top)), 2),
  Loading = c(as.numeric(PC1_top), as.numeric(PC2_top), as.numeric(PC3_top), as.numeric(PC4_top)),
  PC = rep(c("PC1","PC2","PC3","PC4"), each = 10)
)

# Keep sign for coloring
top_df$Sign <- ifelse(c(loadings[names(PC1_top), "PC1"], loadings[names(PC2_top), "PC2"],
                        loadings[names(PC1_top), "PC3"], loadings[names(PC2_top), "PC4"]) > 0, "Positive", "Negative")

# Barplot
p3 <- ggplot(top_df, aes(x = reorder(CellType, Loading), y = Loading, fill = Sign)) +
  geom_bar(stat = "identity") +
  facet_wrap(~PC, scales = "free_x", ncol = 4 ) +
  coord_flip() +
  scale_x_discrete(labels = labels) + 
  scale_fill_manual(values = c("Positive" = "#1b9e77", "Negative" = "#d95f02")) +
  labs(x = "", y = "Absolute Loading") +
  theme_classic()

```

```{r, fig.height=12, fig.width=12}

# combine plots #----
invisible(grid.arrange(
  grobs = list(
    arrangeGrob(p1_grob, top = textGrob(
      "a",
      gp = gpar(fontsize = 12, fontface = "bold"),
      x = unit(0, "npc"),
      hjust = 0
    )),
    arrangeGrob(p2, top = textGrob(
      "b",
      gp = gpar(fontsize = 12, fontface = "bold"),
      x = unit(0, "npc"),
      hjust = 0
    )),
    arrangeGrob(p3, top = textGrob(
      "c",
      gp = gpar(fontsize = 12, fontface = "bold"),
      x = unit(0, "npc"),
      hjust = 0
    ))
  ),
  layout_matrix = rbind(c(1,NA),
                        c(2,2),
                        c(3,3)),
  heights = c(5,3.5,3.5),
  widths = c(8,4)
))
```

